FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish CloudBacktesting.PaymentService.WebApi.Host -c Release -o out --runtime linux-x64

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "CloudBacktesting.PaymentService.WebApi.Host.dll"]