FROM mcr.microsoft.com/dotnet/core/sdk:3.0 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish CloudBacktesting.ApiGateway.WebApi.Host -c Release -o out --runtime linux-x64


FROM mcr.microsoft.com/dotnet/core/aspnet:3.0
WORKDIR /app
ENV ASPNETCORE_ENVIRONMENT=Docker
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "CloudBacktesting.ApiGateway.WebApi.Host.dll"]