FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

COPY . ./
RUN dotnet publish CloudBacktesting.SubscriptionService.WebApi.Host -c Release -o out --runtime linux-x64

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/out .

ENTRYPOINT ["dotnet", "CloudBacktesting.SubscriptionService.WebApi.Host.dll"]