apiVersion: v1
kind: Service
metadata:
  name: consulservice
  
spec:
  type: NodePort
  selector:
    app: consulpod
  ports:
    - port: 8500
      nodePort: 30000
      targetPort: 8500
---
apiVersion: v1
kind: Service
metadata:
  name: jsprojservice
spec:
  type: NodePort
  selector:
    app: jsprojpod
  ports:
  - port: 9095
    targetPort: 9095
    nodePort: 30001


