# apiVersion: v1
# kind: Service
# metadata:
#   name: consulservice
# spec:
#   type: NodePort
#   selector:
#     app: consul
#   ports:
#     - port: 8500
#       nodePort: 30000
#       targetPort: 8500
# ---
apiVersion: v1
kind: Service
metadata:
  name: msservice
spec:
  type: NodePort
  selector:
    app: microservices
  ports:
  - port: 9095
    targetPort: 9095
    nodePort: 30001


