kind: ConfigMap
apiVersion: v1
metadata:
  name: hashicorp-consul-server-config
  namespace: default
  labels:
    app: consul
    chart: consul-0.1.0
    heritage: Helm
    release: hashicorp
data:
  server.json: '
    {
      "autopilot": {
        "cleanup_dead_servers": true,
        "last_contact_threshold": "300ms",
        "max_trailing_logs": 250,
        "server_stabilization_time": "10s"
      },
      "ports": { 
        "http": 8500
      },
      "verify_incoming": true,
      "verify_outgoing": true,
      "verify_server_hostname": true
    }'
