  kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: hashicorp-consul-server
spec:
  selector:
    matchLabels:
      app: consul
  serviceName: consulservice
  replicas: 1
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consulcontainer
          image: "consul"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "agent"
            - "-advertise=$(POD_IP)"
            - "-bind=0.0.0.0"
            - "-bootstrap-expect=1"
            - "-client=0.0.0.0"
            - "-config-file=/consul/config/server.json"
            - "-datacenter=dc1"
            - "-data-dir=/consul/data"
            - "-domain=consul"
            - "-hcl=\"connect { enabled = true }\""
            - "-retry-join=microservices.svc"
            - "-server"
            - "-ui"
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - "-ec"
                - |
                  curl http://127.0.0.1:8500/v1/status/leader 2>/dev/null | \
                  grep -E '".+"'
          volumeMounts:
            - name: data
              mountPath: /consul/data
            - name: config
              mountPath: /consul/config
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - consul leave
          ports:
            - name: dns-tcp
              containerPort: 8600
              protocol: "TCP"
            - name: dns-udp
              containerPort: 8600
              protocol: "UDP"
            - name: http
              containerPort: 8500
              protocol: "TCP"
            - name: https
              containerPort: 8443
              protocol: "TCP"
            - name: serf-lan-tcp
              containerPort: 8301
              protocol: "TCP"
            - name: serf-lan-udp
              containerPort: 8301
              protocol: "UDP"
            - name: serf-wan-tcp
              containerPort: 8302
              protocol: "TCP"
            - name: serf-wan-udp
              containerPort: 8302
              protocol: "UDP"
            - name: server-rpc
              containerPort: 8300
              protocol: "TCP"
          resources:
            requests:
              cpu: "250m"
              memory: "1Gi"
      terminationGracePeriodSeconds: 10
      securityContext:
        fsGroup: 1000
      # volumes:
      #   - name: consul-config
      #     configMap:
      #       name: consul
      #   - name: consul-tls
      #     secret:
      #       secretName: consul
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
